name: Outlook Token Renew Cron

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  renew-outlook:
    runs-on: ubuntu-latest

    steps:
      - name: Call Outlook Renew API
        run: |
          curl -X GET "https://aitserp-30072025.vercel.app/api/helpdesk/outlook-renew?secret=${{ secrets.OUTLOOK_RENEW_SECRET }}"
